### PR TITLE
If we want to actually be back...

### PR DESCRIPTION
**Pull request by keiranrowan**
Since the current repository is going nowhere and the current files seem to be using a hosted environment rather than a freestanding one, it is best we go with a system that is quite already built. Although it may not be to everyone's liking, we can modify it as we need in order to achieve our goal.
Just a thought...

### CODE REVIEW

**Comment by chanhandler** [comment]
this thing is still alive?

**Comment by keiranrowan** [comment]
I doubt. Just a hopeful jump start if anything...

**Comment by keiranrowan** [comment]
So I take it this thing isn't alive

**Comment by keiranrowan** [comment]
He's dead jim...

**Comment by deltadeltadelta** [comment]
I was in the irc discussions.
The plan was a failure from the start.To be honest, if youre interested youre better off contributing to 9front code rather than reinventing the wheel.

**Comment by keiranrowan** [comment]
True. I didn't expect much from /g/ anyways... It ain't what it used to be.

**Pull request closed without merging**
